### ISSUE TITLE
Spot instances support

### ISSUE THREAD

**Issue by ianomad** [cloudposse/terraform-aws-elastic-beanstalk-environment#100]
Beanstalk now support spot instances:
https://aws.amazon.com/about-aws/whats-new/2019/11/aws-elastic-beanstalk-adds-support-for-amazon-ec2-spot-instances/

**Comment by joe-niland** [comment]
Supported since https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/releases/tag/0.20.0
