### ISSUE TITLE
Doesn't support AWS provider v3.x

### ISSUE THREAD

**Issue by antgel** [cloudposse/terraform-aws-elastic-beanstalk-environment#142]
## Describe the Bug
AWS provider version constraint ~> 2.0 doesn't support modules that use ~> 3.x versions. For example, my module supports AWS ~> 3.4.0 and I get:
```
Could not retrieve the list of available versions for provider hashicorp/aws:
no available releases match the given constraints ~> 3.4.0, ~> 2.0, ~> 2.0, ~>
3.4.0
```

**Comment by SweetOps** [comment]
fixed by https://github.com/cloudposse/terraform-aws-elastic-beanstalk-application/pull/31
