### ISSUE TITLE
Feature Request - Add variable for environment tier

### ISSUE THREAD

**Issue by pearson-lucas-dev** [cloudposse/terraform-aws-elastic-beanstalk-environment#21]
Hello @osterman @goruha @aknysh 

Currently, your module for elastic beanstalk environment doesn't have a way to set the tier for the application to be "Worker" because it is hardcoded to "WebServer".  I am asking that a variable is created for the tier with it defaulting to "WebServer" so it disrupts as little as possible. I will put in a PR shortly this Issue number.

Thanks,

Lucas Pearson

**Comment by osterman** [comment]
Thanks for the PR. Merged!
