### ISSUE TITLE
Should *not* be passing the 'Name' tag to elastic beanstalk environment creation

### ISSUE THREAD

**Issue by richardj-bsquare** [cloudposse/terraform-aws-elastic-beanstalk-environment#42]
As per this issue, the 'Name' tag is reserved for use by AWS elastic beanstalk:

https://github.com/terraform-providers/terraform-provider-aws/issues/3963

This results in failures to deploy and non-idempotency issues.

The null label provider is taking the provided tags and 'sanitising' them... But for this module the 'Name' tag needs stripping out.

```
 tags.%:                                        "3" => "5"
      tags.Name:                                     "" => "mine-staging-jenkins2build-eb-env"
      tags.Namespace:                                "" => "mine"
```

How to Reproduce:
This I believe happens in an already provisioned environment, using terraform-aws-jenkins and...
when using version 1.10 and 1.11 of the terraform AWS provider:

* 2018-07-24 14:09:16.652 +0000 UTC (e-mip7mrnszq) : Service:AmazonCloudFormation, Message:No updates are to be performed.
* 2018-07-24 14:09:17.325 +0000 UTC (e-mip7mrnszq) : Environment tag update failed.

**Comment by richardj-bsquare** [comment]
Annoyingly, the tag will be created by beanstalk, and then re-running terraform will result in the need for the tag to be removed ... sigh...

**Comment by i5okie** [comment]
Will this ever be resolved?

**Comment by osterman** [comment]
@richardj-bsquare, @i5okie pull requests are welcome! =) We'll review promptly. 

Thanks!

**Comment by osterman** [comment]
We recently received this PR, which apparently was insufficient. https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/pull/40

**Comment by osterman** [comment]
Also, I welcome both of you to join our community slack where you'll have direct access to me and the rest of the team here. https://slack.cloudposse.com/

**Comment by osterman** [comment]
@richardj-bsquare are you running the latest version with the `lifecycle { ... }` block? I've received reports from others that this works for them.
