### ISSUE TITLE
Validation error: Environment tag cannot be empty

### ISSUE THREAD

**Issue by vlaurin** [cloudposse/terraform-aws-elastic-beanstalk-environment#45]
As part of recent commit https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/commit/93860adaa57eb7d1153f90d6f94fafda68aa255d , the version of module `terraform-null-label` has been updated from `0.3.1` to `0.5.0`.

This seems to have introduced a breaking change in the way the `environment` tag is handled.

Following that change, TF plan indicates that the following tags will be created:

```
  tags.%: "" => "4"
  tags.Environment: "" => ""
  tags.Name: "" => "xxx"
  tags.Namespace:  "" => "yyy"
  tags.Stage: "" => "demo"
```

The only empty tag value is for `tags.Environment`.
It then fails when applying with the error:

```
* aws_elastic_beanstalk_environment.default: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, CreateEnvironmentInput.Tags[1].Value.
```

This is due to the fact that the `label` resource of module `terraform-aws-elastic-beanstalk-environment` does not specify an `environment` variable.

I tried adding the `environment` variable to the resource (https://github.com/vlaurin/terraform-aws-elastic-beanstalk-environment/commit/edd54e1416e9ee120a10cdad900e0bc9d74884b7#diff-7a370d8342e7203b805911c92454f0f4R6) and it does resolve the issue.

**Comment by geekscruff** [comment]
I'm seeing the same problem.

**Comment by aknysh** [comment]
this was fixed in the last release https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/releases/tag/0.4.7

thanks @vlaurin  and @geekscruff
