### ISSUE TITLE
`enhanced` health not supported by some platforms, but cannot be changed

### ISSUE THREAD

**Issue by seanfdnn** [cloudposse/terraform-aws-elastic-beanstalk-environment#51]
Some platforms (i.e. .NET) do not support the enhanced health system, yet there is no option to change this to basic.  Causes the error

```
ConfigurationValidationException: Configuration validation exception: Enhanced health reporting system is not supported by current solution stack
```

Solution would be to add a variable for this.

**Comment by osterman** [comment]
@seanfdnn thanks for reporting this! Seems like an easy fix. 

1. Introduce a new flag: `enhanced_reporting_enabled` here:
https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/blob/master/main.tf#L619
2. Use a ternary here to skip creating the resource if it's not enabled here: https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/blob/master/main.tf#L39

We'll gladly review any PRs, if you are able to submit one.

**Comment by johncblandii** [comment]
Looks like you figured out `count` pretty quickly after this comment, @skolsuper. Good job.
