### ISSUE TITLE
Provide a way to specify visibility for Elastic Load Balancers to be internal 

### ISSUE THREAD

**Issue by ofasterling** [cloudposse/terraform-aws-elastic-beanstalk-environment#58]
Hello,
I recently started using your module and was able to create a new Elastic Beanstalk environment successfully. However, I need my load balancers to be internal facing only. I could not find a way to specify this within the module. The module requires 'public_subnets', so I assume this is functionality is not currently available? 

In AWS, you can specify the visibility as shown in the attached screenshot. Thanks!
![image](https://user-images.githubusercontent.com/12616115/47725948-d6dfee80-dc59-11e8-9969-f3a82bc69257.png)

**Comment by CGreenPayTM** [comment]
https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/pull/72
