### ISSUE TITLE
some unset env vars are making their way into the envrionment

### ISSUE THREAD

**Issue by dnorth98** [cloudposse/terraform-aws-elastic-beanstalk-environment#62]
Hi there,
    Fantastic module.  I've managed to get an EB env up and running with this with around 13 environment variables and all looks good.  Except I seem to be getting 3 "rogue" environment variables being set:

```
DEFAULT_ENV_13
DEFAULT_ENV_27
DEFAULT_ENV_41
```

and only these 3.  I think the way you've handled the environment variables is pretty nice as all the uglyness of EB variables is hidden nicely in the module.  I can't see how I'm only getting properties for these 3 variables though because my env-vars map looks like:

```
   env_vars = "${
      map(
        "AWS_REGION", "${local.aws_region}",
        "BUNDLE_WITHOUT", "test:development",
        "REDIS_PORT", "6379",
        "REDIS_URL", "${local.redis_url}",
        "APPLICATION_NAME", "foo",
        "LOAD_DB", "none",
        "RACK_ENV", "staging",
        "RAILS_SKIP_ASSET_COMPILATION", "false",
        "RAILS_SKIP_MIGRATIONS", "false",
        "RDS_DB_NAME", "mydb",
        "RDS_PORT", "5432",
        "RDS_USERNAME", "myuser",
        "API_URL", "https://api.foo.com"
      )
    }"
```

Any thoughts why I might get the 3 rogues?

**Comment by dnorth98** [comment]
Uh oh.  I think I've found the issue.  This is how the var is obtained:

```
setting {
    namespace = "aws:elasticbeanstalk:application:environment"
    name      = "${element(concat(keys(var.env_vars), list(format(var.env_default_key, 13))), 13)}"
    value     = "${lookup(var.env_vars, element(concat(keys(var.env_vars), list(format(var.env_default_key, 13))), 13), var.env_default_value)}"
  }
```

and this is the docs for the `element` function (notice how it wraps):

> element(list, index) - Returns a single element from a list at the given index. If the index is greater than the number of elements, this function will wrap using a standard mod algorithm. This function only works on flat lists.

It looks like relying on element to fall off the end if there is not a var won't work reliably with element wrapping...

**Comment by skolsuper** [comment]
If you set no env vars (we set ours in `.ebextensions` in the app), you get all 50 default env vars.  Is that a manifestation of this bug?  I'm struggling to understand why I'd want that if not

**Comment by dnorth98** [comment]
Yeah, I think it's related.  The lookup only really works if you use all of the env vars...

**Comment by lodotek** [comment]
Love these modules but I wish they were better maintained! Any progress here at all?

**Comment by mikepc** [comment]
yeah this is really obnoxious having a ton of extra environment variables :( I would rather have *no* default environment variables whatsoever than have to manually delete this nonsense
