### ISSUE TITLE
http_listener_enabled not working for me

### ISSUE THREAD

**Issue by pabardina** [cloudposse/terraform-aws-elastic-beanstalk-environment#74]
Hello !

In my beanstalk env, my load balancer listens on https. I would like to listen on http too, to redirect http -> https. I know, there is already a patch on it, and I'm using the `http_listener_enabled` parameter.

But... It doesn't work for me.

Here a screenshot of AWS console 👍 
<img width="1335" alt="screenshot 2019-02-01 at 10 22 42" src="https://user-images.githubusercontent.com/2794980/52114225-c6019900-260b-11e9-9381-02f27924ae7c.png">

And terraform : 

```
module "elastic_beanstalk_environment" {
  source                              = "git::https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment.git?ref=tags/0.4.8"

...

  healthcheck_url                      = "${var.healthcheck_url}"
  http_listener_enabled	               = true 
  loadbalancer_type                             = "application"
  loadbalancer_certificate_arn        = "${aws_acm_certificate.cert.arn}"

  loadbalancer_security_groups      = ["${module.metabase_sg.this_security_group_id}"]
  loadbalancer_managed_security_group = "${module.metabase_sg.this_security_group_id}"

}
```

tfsate : 
```
"all_settings.232565.namespace": "aws:elbv2:listener:default",
"all_settings.232565.resource": "",
 "all_settings.232565.value": "false",
```

What am I doing wrong?

Thanks

**Comment by aj-jaswanth-ee** [comment]
@pabardina Have you tried specifying true as string `"true"` instead of boolean `true`?

**Comment by aknysh** [comment]
please try the latest version https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/releases/tag/0.44.0
