### ISSUE TITLE
Full access to s3

### ISSUE THREAD

**Issue by sbuljac** [cloudposse/terraform-aws-elastic-beanstalk-environment#75]
Are you aware this
https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/blob/c7f97299d3d323c2c6c258e06d823f27db855ffb/main.tf#L254
creates a role with full access to all s3 buckets?

**Comment by anton-kachurin** [comment]
There is also a managed policy attached to the role called `AmazonEC2RoleforSSM` that grants full access to all s3 buckets. Note that AWS marked this policy as "soon to be deprecated" and suggests to use this one instead: `AmazonSSMManagedInstanceCore`
