### ISSUE TITLE
when beanstalk setting is blank

### ISSUE THREAD

**Issue by debu99** [cloudposse/terraform-aws-elastic-beanstalk-environment#78]
for example like SSLPolicy

the error returns:
Creating Load Balancer listener failed Reason: An SSL policy must be specified for HTTPS listeners

**Comment by AlmogCohen** [comment]
According to [this](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html) I use the recommended setting as `loadbalancer_ssl_policy = "ELBSecurityPolicy-2016-08"` and it all works.

**Comment by AlmogCohen** [comment]
I think this option should be the default of this module, unless there is something I don't see
