### ISSUE TITLE
terraform v.012 support

### ISSUE THREAD

**Issue by lpfeup** [cloudposse/terraform-aws-elastic-beanstalk-environment#86]
Hi, just wanted to know if there are any plans to support [Terraform v0.12](https://www.terraform.io/upgrade-guides/0-12.html) in the near future.

**Comment by aknysh** [comment]
@lpfeup 
we are converting all our modules to TF 0.12.
This module will be converted as well, probably in the next week or so.

**Comment by lpfeup** [comment]
That's great, thank you 👍

**Comment by joshes** [comment]
@aknysh I know (and appreciate) there are a lot of modules and TF 0.12 migrations; any chance for a rough ETA on this one?

**Comment by jakubgs** [comment]
Any news on this? I just accidentally converted my state to `0.12` by using wrong TF binary, and now I can't use this module anymore... my stupidity sometimes amazes me.

**Comment by lodotek** [comment]
@jakubgs for now you can use my fork if you would like, see the differences here: https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/compare/master...lodotek:master

Pretty easy to upgrade the module to support v0.12

**Comment by jakubgs** [comment]
That's amazing @lodotek ! Saved my ass, appreciate it!

**Comment by jakubgs** [comment]
I owe you a beer or a few @lodotek, it works!

**Comment by lodotek** [comment]
Haha awesome! Glad I was able to help :-)

**Comment by rcmgleite** [comment]
Is there any plan to merge @lodotek's PR?
Currently this is the only blocker to use this project!

**Comment by lodotek** [comment]
See here: https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/pull/87#issuecomment-519181071
